### ISSUE TITLE
initalize submodule "mth_tpswitch" 

### ISSUE THREAD

**Issue by hunsa** [massivethreads/tp-parsec#1]
The following call seems to be missing from the README
`
git submodule update --init toolkit/tp_parsec/mth_tpswitch
`

If not initialized, when building a benchmark, we run into
`
 fatal error: ../mth_tpswitch/src/tpswitch/tpswitch.h: No such file or directory
`

**Comment by zanton** [comment]
Thank you very much.
It was an obvious defect in README.
